# Generated by Django 4.1.1 on 2022-09-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to="poll_api.user",
            ),
            preserve_default=False,
        ),
    ]
