# Generated by Django 4.1.1 on 2022-11-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="closing_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="poll", name="end_date", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="poll", name="start_date", field=models.DateField(null=True),
        ),
    ]
