# Generated by Django 4.1.3 on 2022-12-02 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll_api", "0002_poll_closing_time_poll_end_date_poll_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="creation_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 2, 12, 34, 52, 596964)
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="currency",
            field=models.CharField(
                choices=[("eu", "Eu"), ("usd", "Usd")], default="eu", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="choice", name="price", field=models.FloatField(default=0),
        ),
    ]
