# Generated by Django 4.1.1 on 2022-09-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll_api", "0002_poll_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="polls",
            field=models.ManyToManyField(
                blank=True, through="poll_api.Participant", to="poll_api.poll"
            ),
        ),
        migrations.AlterField(
            model_name="poll",
            name="participants",
            field=models.ManyToManyField(
                blank=True, through="poll_api.Participant", to="poll_api.user"
            ),
        ),
    ]
