# Generated by Django 4.1.3 on 2022-12-15 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("poll_api", "0003_choice_creation_time_choice_currency_choice_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="creation_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="poll",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("locked", "Locked"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="choice",
            name="creation_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="choice",
            name="link",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
