# Generated by Django 4.1.1 on 2022-09-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("poll_api", "0003_user_polls_alter_poll_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="poll_api.participant",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="poll_api.choice",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="poll_api.participant",
            ),
        ),
    ]
